#!/usr/bin/env bash
# Haproxy configurations
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/sibusiso24.tech/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    acl is_root path -i /
    use_backend backend-www if is_root

backend backend-www
    server 259888-web-01 18.204.10.209

frontend www-http
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }
