#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
# print  "bad luck" for the 4th iteration
# print  "good luck" for the 8th iteration
# print  "Best School" for all other iterations

bala=0

while [ $bala -lt 10 ]
do
  if [ $bala -eq 3 ]
  then
    echo "bad luck"
  elif [ $bala -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( bala++ ))
done
